### ISSUE TITLE
Not working with messageformat ^2.0.0

### ISSUE THREAD

**Issue by elekdavid** [lephyrus/ngx-translate-messageformat-compiler#22]
**I tried the following setup**
```
messageformat: 2.0.1
ngx-translate-messageformat-compiler: 3.0.0
```

**Got following error at bootstrap time**
```
ERROR TypeError: (intermediate value).setBiDiSupport(...).setIntlSupport is not a function
    at new TranslateMessageFormatCompiler (translate-message-format-compiler.js:33)
    at _createClass (core.js:10891)
    at _createProviderInstance$1 (core.js:10865)
    at resolveNgModuleDep (core.js:10850)
    at _createClass (core.js:10899)
    at _createProviderInstance$1 (core.js:10865)
    at resolveNgModuleDep (core.js:10850)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)
```

**Possible solution**
`#setIntlSupport()` function has been removed from `messageformat` at `v2.0.0` (see [release notes](https://github.com/messageformat/messageformat/releases/tag/v2.0.0)), but in `TranslateMessageFormatCompiler` this function is called in [ln20](https://github.com/lephyrus/ngx-translate-messageformat-compiler/blob/17b54c199b94452df75b05cccd50fcb3a7da2eca/src/translate-message-format-compiler.ts#L20)

**Comment by rafa-as** [comment]
Same here!

**Comment by legvalmont** [comment]
I've solved this issue on v3.0.1 by installing messageformat 1.x.x as a dependency of my own project. The following command is the one I issued:

`$ npm install messageformat@1 --save`

@lephyrus can I suggest you include a dependency change for messageformat (forcing 1.x.x) in a future 3.0.2? Because in the end I believe that ngx-translate-messageformat-compiler 3.0.1 pulls the latest messageformat. And that breaks us angular 5- users.

**Comment by lephyrus** [comment]
@legvalmont This library does not pull in any version of `messageformat`. It is specified as a "peer dependency", which means you have to install a compatible version yourself. For v3 of this library, you have to install v1 of `messageformat`, so you've done the right thing. NPM should have showed you a warning when you combined ngx-translate-messageformat-compiler v3 with messageformat v1.
